version: '3.8'  # Specify the version of Docker Compose

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"  # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

  app:
    build: .
    ports:
      - "8080:8080"  # Expose the Spring Boot application on port 8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/pass-genius  # Connection string to MongoDB
      JWT_SECRET: f4f8ab275d167fc80b2e4b4ac940a670a4ebeef571296ce5e3b660b139260735
      JWT_KEY: jgiorjgAF61lsdfmQHGDF45ewrfwe
    depends_on:
      - mongo  # Ensure the MongoDB service starts before the app

volumes:
  mongo-data:  # Define a volume for MongoDB data persistence
